truncate table account CASCADE ;
truncate table article_image CASCADE;
truncate table article_keyword CASCADE;
truncate table article CASCADE;
truncate table article_author CASCADE;
truncate table game_category CASCADE ;
truncate table category CASCADE ;
truncate table game_creator CASCADE ;
truncate table creator CASCADE ;
truncate table game_image CASCADE ;
truncate table game_theme CASCADE ;
truncate table image CASCADE ;
truncate table keyword CASCADE ;
truncate table loan CASCADE ;
truncate table game_copy CASCADE ;
truncate table game CASCADE ;
truncate table loan_status CASCADE ;
truncate table product_line CASCADE ;
truncate table publisher CASCADE ;
truncate table seller CASCADE ;
truncate table contact CASCADE ;
truncate table theme CASCADE ;